apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: campusconnect
  labels:
    app: backend
    tier: backend
spec:
  selector:
    app: backend
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP