apiVersion: apps/v1
kind: Deployment
metadata:
  name: campusconnect-frontend
  labels:
    app: campusconnect-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: campusconnect-frontend
  template:
    metadata:
      labels:
        app: campusconnect-frontend
    spec:
      containers:
        - name: frontend
          image: registry.example.com/campusconnect-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi