apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: campusconnect
resources:
  - namespace.yaml
  - mongo-statefulset.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml